### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by elfranne** [cgrates/cgradmin#3]
I tried to install cgradmin, here is what I did:
# written for Debian 8
# install Go

apt-get install golang
mkdir ~/golang/packages
echo "export GOPATH=~/golang/packages/" > ~/.bashrc
source ~/.bashrc
# install Goji:

go get github.com/zenazn/goji
# not sure you should actually do this :

go get github.com/cgrates/cgradmin
# get cgradmin:

cd /var/www/
git clone https://github.com/cgrates/cgradmin.git
# set config dir:

cgr-engine -config_dir /usr/share/cgrates/conf/samples/cgradmin
# install the extra dependencies for the webui:

apt-get install npm
npm install -g bower
# npm don t get that node is actually nodejs

ln -s /usr/bin/nodejs /usr/bin/node
# will install all the deps in bower.json :

cd /var/www/cgradmin/static
bower --allow-root install
# start the webui:

cd /var/www/cgradmin  
go run main.go

and remember to edit main.go to change the root password.

Did I miss anything ? Is there something that need to change/edit ?
Do i actually need to install the go package for cgradmin ? 

Should I make this into a guide under the current repo or under the cgrates repo so it can be added into http://cgrates.readthedocs.org/en/latest/tutorials.html ? or both ?

**Comment by rif** [comment]
Unfortunately this entire project is left unattended as there are other pressing features in the CGRateS main project that are stealing our attention.
If you are interested in this project please keep watching it as it will receive more love after we release a long term support version for the main project.

**Comment by elfranne** [comment]
Any roadmap for an LTS release ?

**Comment by rif** [comment]
unfortunately because we failed in our estimations so far the best you can do is to monitor the issues and you'll get a feeling of our progress.

**Comment by elfranne** [comment]
Thanks, I ll keep an eye on the main project.
